# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJYWWY41rnS8wtYa1dMhwBbsw8ph2a3C
"""

# 1. Gerekli kütüphaneleri yükle
!pip install gradio

import gradio as gr
import joblib
import pandas as pd
import numpy as np

# 2. Kayıtlı model ve encoder'ı yükle
try:
    model = joblib.load('sensor_model_pipeline.joblib')
    le = joblib.load('label_encoder.joblib')
    class_names = le.classes_
    print("Model ve LabelEncoder başarıyla yüklendi.")
except FileNotFoundError:
    print("HATA: Model (.joblib) dosyaları bulunamadı. Lütfen önce modeli eğitin ve kaydedin.")
    model = None
    le = None

# 3. Dropdown menüler için seçenekler
options = {
    'Operational Status': ['Operational', 'Under Maintenance'],
    'Maintenance Type': ['Corrective', 'Preventive'],
    'Failure History': ['Fault Detected', 'No Fault'],
    'External Factors': ['Clear Weather', 'Storm'],
    'Equipment Relationship': ['Dependent', 'Independent'],
    'Equipment Criticality': ['High', 'Medium']
}

# 4. Modeli çalıştıracak tahmin fonksiyonu (Döndürülen değer güncellendi)
def predict_failure_type(
    # 11 Sayısal Sütun
    Voltage_V, Current_A, Temperature_C, Power_W, Humidity_Percent,
    Vibration_ms2, Ambient_Temperature_C, Ambient_Humidity_Percent,
    X, Y, Z,
    # 6 Kategorik Sütun
    Operational_Status, Maintenance_Type, Failure_History,
    External_Factors, Equipment_Relationship, Equipment_Criticality
):

    if model is None or le is None:
        return "Model yüklenemedi", pd.DataFrame({"Failure Type": ["Hata"], "Probability": [1.0]})

    # Gelen verileri modelin beklediği DataFrame'e dönüştür
    input_df = pd.DataFrame([
        {
            "Voltage (V)": Voltage_V, "Current (A)": Current_A, "Temperature (°C)": Temperature_C,
            "Power (W)": Power_W, "Humidity (%)": Humidity_Percent, "Vibration (m/s²)": Vibration_ms2,
            "Ambient Temperature (°C)": Ambient_Temperature_C, "Ambient Humidity (%)": Ambient_Humidity_Percent,
            "X": X, "Y": Y, "Z": Z, "Operational Status": Operational_Status,
            "Maintenance Type": Maintenance_Type, "Failure History": Failure_History,
            "External Factors": External_Factors, "Equipment Relationship": Equipment_Relationship,
            "Equipment Criticality": Equipment_Criticality
        }
    ])

    # Tahmin olasılıklarını al
    probabilities = model.predict_proba(input_df)[0]

    # Sınıf isimleri ve olasılıkları eşleştir
    confidences = {class_names[i]: float(probabilities[i]) for i in range(len(class_names))}

    # En yüksek olasılığa sahip tahmini bul
    prediction_label = class_names[np.argmax(probabilities)]

    # 1. Çıktı: Risk Durumu (Textbox için)
    if prediction_label == 'None':
        risk_status = "✅ DÜŞÜK RİSK (Arıza Tespit Edilmedi)"
    else:
        risk_status = f"🔥 YÜKSEK RİSK (Tahmin: {prediction_label})"

    # 2. Çıktı: Grafik Verisi (BarPlot için)
    # gr.BarPlot, DataFrame'i sever (örn: [["None", 0.9], ["Overload", 0.1], ...])
    plot_data = pd.DataFrame(confidences.items(), columns=["Failure Type", "Probability"])

    # İki çıktı döndür:
    return risk_status, plot_data

# 5. Gradio Arayüzünü Tanımla (gr.Blocks ile)

# Örnek veri
example_data = [
    112, 0.7, 22, 78.4, 42, 0.3, 22, 42, 2, 2, 2,
    "Operational", "Preventive", "No Fault", "Clear Weather", "Dependent", "High"
]

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🤖 Kestirimci Bakım Modeli Arayüzü")
    gr.Markdown("Sensör verilerini girin ve arıza tipini (None, Overload, Overheating) tahmin edin.")

    with gr.Row():
        # Çıktı Bölümü (Güncellendi)
        with gr.Column(scale=1):
            gr.Markdown("## ⚡️ Tahmin Sonucu")
            output_risk = gr.Textbox(label="Risk Durumu", interactive=False)

            # --- YENİ GRAFİK BİLEŞENİ ---
            # gr.Label'i gr.BarPlot ile değiştirdik
            output_plot = gr.BarPlot(
                label="Tahmin Olasılık Dağılımı",
                x="Failure Type",  # DataFrame'deki sütun adı
                y="Probability", # DataFrame'deki sütun adı
                y_lim=[0, 1],      # Y eksenini 0 ile 1 arasında sabitle
                color="Failure Type", # Sütunları sınıf ismine göre renklendir (Opsiyonel)
                vertical=True,   # Dikey çubuklar
                tooltip=["Failure Type", "Probability"] # Üzerine gelince göster
            )
            # -------------------------------

            submit_btn = gr.Button("Tahmin Et (Submit)", variant="primary")

        # Girdi Bölümü (Değişiklik yok)
        with gr.Column(scale=2):
            gr.Markdown("## 📊 Sensör Veri Girişi")
            with gr.Group():
                gr.Markdown("#### Temel Sensör Verileri")
                with gr.Row():
                    v = gr.Number(label="Voltage (V)", value=example_data[0])
                    c = gr.Number(label="Current (A)", value=example_data[1])
                    t = gr.Number(label="Temperature (°C)", value=example_data[2])
                with gr.Row():
                    p = gr.Number(label="Power (W)", value=example_data[3])
                    h = gr.Number(label="Humidity (%)", value=example_data[4])
                    vib = gr.Number(label="Vibration (m/s²)", value=example_data[5])

            with gr.Group():
                gr.Markdown("#### Ekipman Durumu ve Ortam")
                with gr.Row():
                    op_status = gr.Dropdown(label="Operational Status", choices=options['Operational Status'], value=example_data[11])
                    maint_type = gr.Dropdown(label="Maintenance Type", choices=options['Maintenance Type'], value=example_data[12])
                    fail_hist = gr.Dropdown(label="Failure History", choices=options['Failure History'], value=example_data[13])
                with gr.Row():
                    ext_fact = gr.Dropdown(label="External Factors", choices=options['External Factors'], value=example_data[14])
                    equip_rel = gr.Dropdown(label="Equipment Relationship", choices=options['Equipment Relationship'], value=example_data[15])
                    equip_crit = gr.Dropdown(label="Equipment Criticality", choices=options['Equipment Criticality'], value=example_data[16])

            with gr.Group():
                gr.Markdown("#### Diğer Veriler")
                with gr.Row():
                    amb_t = gr.Number(label="Ambient Temperature (°C)", value=example_data[6])
                    amb_h = gr.Number(label="Ambient Humidity (%)", value=example_data[7])
                with gr.Row():
                    x = gr.Number(label="X", value=example_data[8])
                    y = gr.Number(label="Y", value=example_data[9])
                    z = gr.Number(label="Z", value=example_data[10])

    # Tüm giriş bileşenlerini bir listeye topla
    inputs = [
        v, c, t, p, h, vib, amb_t, amb_h, x, y, z,
        op_status, maint_type, fail_hist, ext_fact, equip_rel, equip_crit
    ]

    # Çıktıları listele (Güncellendi)
    outputs = [output_risk, output_plot]

    # Butona tıklandığında ne olacağını tanımla
    submit_btn.click(
        fn=predict_failure_type,  # Tahmin fonksiyonunu çağır
        inputs=inputs,            # Bu girdilerle
        outputs=outputs           # Bu çıktıları güncelle
    )

    # Örnek Veri Butonu (Güncellendi)
    gr.Examples(
        examples=[example_data],
        inputs=inputs,
        outputs=outputs,
        fn=predict_failure_type,
        cache_examples=False
    )

# 6. Arayüzü Başlat
print("Gelişmiş Gradio arayüzü (Grafik destekli) başlatılıyor...")
demo.launch(share=True, debug=True)

